# Tutorial Island (completed before routine starts)
IRON_STARTER_PART1

QUEST:COOKS_ASSISTANT

QUEST:SHEEP_SHEARER

# QUEST:MISTHALIN_MYSTERY - not supported

QUEST:THE_RESTLESS_GHOST

QUEST:X_MARKS_THE_SPOT

QUEST:WITCHS_POTION

QUEST:CLIENT_OF_KOUREND

# Partially complete: PIRATES_TREASURE - will complete fully later
QUEST:PIRATES_TREASURE

# Unlock: Stronghold of Security - special unlock, not quest

QUEST:CHILDREN_OF_THE_SUN

QUEST:ROMEO_AND_JULIET

QUEST:GERTRUDES_CAT

QUEST:DADDYS_HOME

QUEST:NATURAL_HISTORY_QUIZ

QUEST:RUNE_MYSTERIES

QUEST:TREE_GNOME_VILLAGE

QUEST:HAZEEL_CULT

QUEST:CLOCK_TOWER

QUEST:MONKS_FRIEND

QUEST:PLAGUE_CITY

QUEST:BIOHAZARD

DIARY:ARDOUGNE_EASY

QUEST:FIGHT_ARENA

QUEST:SHEEP_HERDER

QUEST:DWARF_CANNON

# Unlock: Barbarian Assault teleport - special unlock

# Partially complete Alfred Grimhand's Barcrawl - will complete fully later
QUEST:BARCRAWL

QUEST:WATERFALL_QUEST

QUEST:MURDER_MYSTERY

QUEST:MERLINS_CRYSTAL

QUEST:HOLY_GRAIL

QUEST:DRUIDIC_RITUAL

QUEST:WITCHS_HOUSE

# QUEST:BELOW_ICE_MOUNTAIN - not supported

QUEST:BLACK_KNIGHTS_FORTRESS

# QUEST:PIRATE'S_TREASURE - already done above

QUEST:OBSERVATORY_QUEST

QUEST:PRIEST_IN_PERIL

# Partially complete: Rag and Bone Man I - will complete fully later

QUEST:NATURE_SPIRIT

QUEST:RECRUITMENT_DRIVE

# Alfred Grimhand's Barcrawl - already done above

QUEST:SCORPION_CATCHER

QUEST:JUNGLE_POTION

QUEST:VAMPYRE_SLAYER

SKILL:FIREMAKING:4

QUEST:A_PORCINE_OF_INTEREST

# QUEST:RAG_AND_BONE_MAN_I - not supported

# Partially complete: Rag and Bone Man II - not supported

SKILL:COOKING:15

QUEST:DEATH_PLATEAU

QUEST:THE_QUEEN_OF_THIEVES

SKILL:AGILITY:18

QUEST:THE_DEPTHS_OF_DESPAIR

QUEST:MOUNTAIN_DAUGHTER

SKILL:AGILITY:25

QUEST:THE_GRAND_TREE

QUEST:TRIBAL_TOTEM

QUEST:THE_DIG_SITE

QUEST:THE_GOLEM

QUEST:THE_KNIGHTS_SWORD

QUEST:ELEMENTAL_WORKSHOP_I

QUEST:DEMON_SLAYER

QUEST:SHADOW_OF_THE_STORM

SKILL:MAGIC:20

# QUEST:ELEMENTAL_WORKSHOP_II - not supported

SKILL:WOODCUTTING:15

# QUEST:THE_RIBBITING_TALE_OF_A_LILY_PAD_LABOUR_DISPUTE - not supported

SKILL:WOODCUTTING:36

SKILL:FIREMAKING:16

DIARY:LUMBRIDGE_EASY

QUEST:LOST_CITY

QUEST:FAIRYTALE_I
MILESTONE:FAIRY_RINGS

QUEST:RFD_COOK

QUEST:GOBLIN_DIPLOMACY

QUEST:RFD_GOBLINS

QUEST:SLEEPING_GIANTS

QUEST:SHIELD_OF_ARRAV

QUEST:CREATURE_OF_FENKENSTRAIN

# QUEST:A_SOUL'S_BANE - not supported

QUEST:THE_LOST_TRIBE

# QUEST:DEATH_TO_THE_DORGESHUUN - not supported

QUEST:IMP_CATCHER

SKILL:MAGIC:33

# QUEST:THE_GIANT_DWARF - not supported

# QUEST:ANOTHER_SLICE_OF_H.A.M. - not supported

QUEST:MAKING_HISTORY

QUEST:IN_SEARCH_OF_THE_MYREQUE

# QUEST:SHADES_OF_MORT'TON - not supported

# QUEST:IN_AID_OF_THE_MYREQUE - not supported

# Unlock: Varrock Museum Kudos - special unlock

QUEST:BONE_VOYAGE

QUEST:ENTER_THE_ABYSS

QUEST:WANTED

QUEST:THE_FEUD

QUEST:TROLL_STRONGHOLD

SKILL:WOODCUTTING:45

QUEST:TROLL_ROMANCE

QUEST:DRAGON_SLAYER_I

QUEST:HORROR_FROM_THE_DEEP

QUEST:ERNEST_THE_CHICKEN

QUEST:ANIMAL_MAGNETISM

QUEST:SHILO_VILLAGE

QUEST:DORICS_QUEST

SKILL:RANGED:37

# QUEST:SPIRITS_OF_THE_ELID - not supported

QUEST:ICTHLARINS_LITTLE_HELPER

QUEST:ETHICALLY_ACQUIRED_ANTIQUITIES

QUEST:TWILIGHTS_PROMISE

QUEST:DEATH_ON_THE_ISLE

# QUEST:RATCATCHERS - not supported

QUEST:THE_GARDEN_OF_DEATH

SKILL:FIREMAKING:20

QUEST:ENLIGHTENED_JOURNEY

SKILL:FIREMAKING:30

# Unlock: Balloon transport system to Crafting Guild - special unlock

QUEST:SEA_SLUG

QUEST:FISHING_CONTEST

QUEST:RFD_DWARF
MILESTONE:ROCK_CAKE

SKILL:COOKING:22

QUEST:GHOSTS_AHOY

# QUEST:FORGETTABLE_TALE - not supported

# QUEST:GARDEN_OF_TRANQUILLITY - not supported

QUEST:RFD_EVIL_DAVE

QUEST:BIG_CHOMPY_BIRD_HUNTING

QUEST:ZOGRE_FLESH_EATERS

SKILL:HERBLORE:30

DIARY:VARROCK_EASY

# Easy Desert Diary - diary system not implemented

# QUEST:DARKNESS_OF_HALLOWVALE - not supported

QUEST:TOWER_OF_LIFE

QUEST:RFD_PIRATE

# Easy Falador Diary - diary system not implemented

# QUEST:TAI_BWO_WANNAI_TRIO - not supported

QUEST:THE_TOURIST_TRAP

SKILL:FLETCHING:25

# QUEST:EADGAR'S_RUSE - not supported

# QUEST:MY_ARM'S_BIG_ADVENTURE - not supported

QUEST:THE_FREMENNIK_TRIALS

SKILL:CONSTRUCTION:20

SKILL:WOODCUTTING:56

SKILL:CRAFTING:46

# QUEST:THE_FREMENNIK_ISLES - not supported

QUEST:GETTING_AHEAD

SKILL:COOKING:41

QUEST:RFD_GUIDE

# QUEST:RFD_SKRACH_UGLOGWEE - not supported

QUEST:HAUNTED_MINE

SKILL:MINING:40

# Easy Karamja Diary - diary system not implemented

QUEST:WATCHTOWER

QUEST:PRINCE_ALI_RESCUE

# QUEST:CONTACT - not supported

SKILL:MAGIC:46

QUEST:THE_EYES_OF_GLOUPHRIE

QUEST:TEMPLE_OF_THE_EYE

SKILL:FIREMAKING:50

# Unlock: Balloon transport system to Varrock - special unlock

# QUEST:OLAF'S_QUEST - not supported

# QUEST:TEARS_OF_GUTHIX - not supported

SKILL:RANGED:40

QUEST:TEMPLE_OF_IKOV

QUEST:ONE_SMALL_FAVOUR

# QUEST:A_TAIL_OF_TWO_CATS - not supported

SKILL:SMITHING:50

SKILL:SLAYER:30

# QUEST:THE_SLUG_MENACE - not supported

# QUEST:BETWEEN_A_ROCK - not supported

QUEST:MONKEY_MADNESS_I

SKILL:CONSTRUCTION:34

SKILL:HUNTER:12

# QUEST:COLD_WAR - not supported

QUEST:THE_ASCENT_OF_ARCEUUS

SKILL:HUNTER:27

# QUEST:EAGLES'_PEAK - not supported

QUEST:UNDERGROUND_PASS

SKILL:SLAYER:42

# QUEST:SKIPPY_AND_THE_MOGRES - not supported

# QUEST:RAG_AND_BONE_MAN_II - not supported

# QUEST:LAIR_OF_TARN_RAZORLOR - not supported

SKILL:FISHING:50

SKILL:PRAYER:47

SKILL:FARMING:40

QUEST:RUM_DEAL

QUEST:CABIN_FEVER

# QUEST:HIS_FAITHFUL_SERVANTS - not supported

# QUEST:THE_GREAT_BRAIN_ROBBERY - not supported

SKILL:CONSTRUCTION:38

# QUEST:SCRAMBLED - not supported

SKILL:CRAFTING:50

QUEST:THE_HAND_IN_THE_SAND

SKILL:MINING:45

# QUEST:ENAKHRA'S_LAMENT - not supported

# QUEST:MEAT_AND_GREET - not supported

SKILL:MINING:50

SKILL:COOKING:53

SKILL:FISHING:53

QUEST:HEROES_QUEST

QUEST:THRONE_OF_MISCELLANIA

QUEST:ROYAL_TROUBLE

SKILL:MAGIC:50

SKILL:THIEVING:53

QUEST:DESERT_TREASURE_I

SKILL:MAGIC:59

SKILL:MINING:52

SKILL:AGILITY:50
MILESTONE:ROGUES_OUTFIT

# QUEST:A_TASTE_OF_HOPE - not supported

QUEST:FAMILY_CREST

# QUEST:LEGENDS_QUEST - not supported

# QUEST:RFD_SIR_AMIK_VARZE - not supported

# QUEST:CURSE_OF_THE_EMPTY_LORD - not supported

# QUEST:THE_GENERAL'S_SHADOW - not supported

SKILL:FARMING:47

# All Easy Achievement Diaries - diary system not implemented

# Medium diaries - diary system not implemented

SKILL:FLETCHING:50

# QUEST:LAND_OF_THE_GOBLINS - not supported

SKILL:FARMING:49

# QUEST:FAIRYTALE_II - not supported

QUEST:TALE_OF_THE_RIGHTEOUS

QUEST:THE_FORSAKEN_TOWER

SKILL:AGILITY:54

QUEST:A_KINGDOM_DIVIDED

SKILL:SLAYER:48

SKILL:MINING:55

# QUEST:THE_HEART_OF_DARKNESS - not supported

# QUEST:PERILOUS_MOONS - not supported

SKILL:COOKING:70

QUEST:RFD_MONKEY

SKILL:AGILITY:56

QUEST:REGICIDE

QUEST:ROVING_ELVES

SKILL:RANGED:60

QUEST:MOURNINGS_END_PART_I

QUEST:MOURNINGS_END_PART_II

SKILL:MAGIC:65

SKILL:CRAFTING:61

SKILL:MINING:60

QUEST:LUNAR_DIPLOMACY

QUEST:WHAT_LIES_BELOW

SKILL:DEFENCE:65

QUEST:KINGS_RANSOM
MILESTONE:UNLOCK_PIETY

SKILL:MAGIC:66

SKILL:FISHING:62

# QUEST:SWAN_SONG - not supported

QUEST:RFD_CULINAROMANCER

SKILL:WOODCUTTING:71

SKILL:THIEVING:58

# QUEST:GRIM_TALES - not supported

SKILL:SLAYER:69

# QUEST:DREAM_MENTOR - not supported

SKILL:HUNTER:46

DIARY:LUMBRIDGE_MEDIUM

# QUEST:AT_FIRST_LIGHT - not supported

SKILL:HUNTER:52

SKILL:SMITHING:55

# QUEST:DEFENDER_OF_VARROCK - not supported

# Medium diaries - diary system not implemented

SKILL:SMITHING:65

SKILL:RUNECRAFTING:50

# QUEST:DEVIOUS_MINDS - not supported

SKILL:RUNECRAFTING:52

SKILL:FLETCHING:52

SKILL:THIEVING:66

# QUEST:THE_FINAL_DAWN - not supported

SKILL:SLAYER:54

SKILL:CONSTRUCTION:41

# QUEST:SHADOWS_OF_CUSTODIA - not supported

SKILL:SLAYER:56

# QUEST:THE_PATH_OF_GLOUPHRIE - not supported

SKILL:CRAFTING:65

SKILL:SLAYER:60

SKILL:RUNECRAFTING:55

SKILL:FISHING:60

# QUEST:THE_FREMENNIK_EXILES - not supported

SKILL:FLETCHING:60

# QUEST:SINS_OF_THE_FATHER - not supported

SKILL:AGILITY:62

SKILL:FIREMAKING:55

# QUEST:BENEATH_CURSED_SANDS - not supported

SKILL:MINING:64

SKILL:RANGED:62

SKILL:STRENGTH:58

# QUEST:THE_CURSE_OF_ARRAV - not supported

SKILL:AGILITY:68

SKILL:MINING:72

SKILL:FIREMAKING:66

# QUEST:MAKING_FRIENDS_WITH_MY_ARM - not supported

SKILL:CRAFTING:70

SKILL:HUNTER:60

SKILL:SLAYER:69

# QUEST:MONKEY_MADNESS_II - not supported

# Medium Fremennik Diary - diary system not implemented

# QUEST:A_NIGHT_AT_THE_THEATRE - not supported

SKILL:CONSTRUCTION:50

SKILL:MAGIC:75

SKILL:SMITHING:70

# QUEST:DRAGON_SLAYER_II - not supported

# QUEST:SECRETS_OF_THE_NORTH - not supported

SKILL:FARMING:65

SKILL:THIEVING:72

# QUEST:WHILE_GUTHIX_SLEEPS - not supported

SKILL:CONSTRUCTION:70

SKILL:FARMING:70

SKILL:HERBLORE:70

SKILL:HUNTER:70

# QUEST:SONG_OF_THE_ELVES - not supported

SKILL:FIREMAKING:75

SKILL:RUNECRAFTING:60

# QUEST:DESERT_TREASURE_II - not supported

# All Skills quest XP rewards from this point do not impact any other quests

QUEST:THE_CORSAIR_CURSE