IRON_STARTER_PART1
# DONE IN THE STARTER
# QUEST:BLACK_KNIGHTS_FORTRESS
# QUEST:COOKS_ASSISTANT
# QUEST:ERNEST_THE_CHICKEN
# QUEST:GOBLIN_DIPLOMACY
# QUEST:THE_KNIGHTS_SWORD
# QUEST:THE_RESTLESS_GHOST
# QUEST:RUNE_MYSTERIES
# QUEST:SHEEP_SHEARER
# QUEST:WITCHS_POTION
# QUEST:X_MARKS_THE_SPOT
# QUEST:CHILDREN_OF_THE_SUN
# QUEST:CLIENT_OF_KOUREND
# QUEST:CLOCK_TOWER
# QUEST:DRUIDIC_RITUAL
# QUEST:DWARF_CANNON
# QUEST:FIGHT_ARENA
# QUEST:FISHING_CONTEST
# QUEST:THE_FORSAKEN_TOWER
# QUEST:GERTRUDES_CAT
# QUEST:HAZEEL_CULT
# QUEST:MONKS_FRIEND
# QUEST:MURDER_MYSTERY
# QUEST:OBSERVATORY_QUEST
# QUEST:PLAGUE_CITY
# QUEST:THE_QUEEN_OF_THIEVES
# QUEST:RFD_COOK
# QUEST:RFD_DWARF
# QUEST:RFD_GOBLINS
# QUEST:SEA_SLUG
# QUEST:TALE_OF_THE_RIGHTEOUS
# QUEST:TREE_GNOME_VILLAGE
# QUEST:TRIBAL_TOTEM
# QUEST:WATERFALL_QUEST
# QUEST:WITCHS_HOUSE
# QUEST:DADDYS_HOME
# SKILL:THIEVING:54
# SKILL:FLETCHING:10
# SKILL:MINING:23
# SKILL:FISHING:42
# SKILL:COOKING:39
# SKILL:FIREMAKING:50
# SKILL:WOODCUTTING:48
# END STARTER

DIARY:ARDOUGNE_EASY

## Fairy Rings
QUEST:RECRUITMENT_DRIVE
QUEST:THE_TOURIST_TRAP
QUEST:THE_LOST_TRIBE
QUEST:JUNGLE_POTION
QUEST:THE_DIG_SITE
QUEST:THE_GRAND_TREE
QUEST:IMP_CATCHER
QUEST:SHIELD_OF_ARRAV
QUEST:DEMON_SLAYER
QUEST:NATURAL_HISTORY_QUIZ
QUEST:BONE_VOYAGE
SKILL:THIEVING:61 # Money for Compost

REPEATING:COMPOST_RUNS

QUEST:ELEMENTAL_WORKSHOP_I

QUEST:ENTER_THE_ABYSS

### Magic Exp
SKILL:MINING:41


QUEST:PRIEST_IN_PERIL
QUEST:NATURE_SPIRIT
ACQUIRE:Molten Glass,1-200
SKILL:CRAFTING:31
QUEST:LOST_CITY

### Gem Unlocks
SKILL:AGILITY:32
QUEST:JUNGLE_POTION
QUEST:SHILO_VILLAGE

SKILL:CONSTRUCTION:25

REPEATING:BIRDHOUSES:99
REPEATING:TREE_RUNS:99
REPEATING:HERB_RUNS:99
REPEATING:SEAWEED_RUNS:99
REPEATING:HESPORI

ACQUIRE:Cooked karambwan,18-54&Swordfish,18-54
QUEST:FAIRYTALE_I
MILESTONE:FAIRY_RINGS