# While Guthix Sleeps
QUEST:SHIELD_OF_ARRAV
QUEST:TEMPLE_OF_IKOV
#QUEST:BELOW_ICE_MOUNTAIN  # Not available in configuration
QUEST:FAMILY_CREST
QUEST:WHAT_LIES_BELOW
QUEST:ROMEO_AND_JULIET
QUEST:DEMON_SLAYER
#QUEST:GARDEN_OF_TRANQUILLITY  # Not available in configuration
QUEST:CREATURE_OF_FENKENSTRAIN
QUEST:PRIEST_IN_PERIL
QUEST:THE_RESTLESS_GHOST
#QUEST:THE_PATH_OF_GLOUPHRIE  # Not available in configuration
QUEST:THE_EYES_OF_GLOUPHRIE
QUEST:THE_GRAND_TREE
QUEST:WATERFALL_QUEST
QUEST:TREE_GNOME_VILLAGE
QUEST:FIGHT_ARENA
#QUEST:DREAM_MENTOR  # Not available in configuration
#QUEST:EADGARS_RUSE  # Not available in configuration
QUEST:DRUIDIC_RITUAL
QUEST:TROLL_STRONGHOLD
QUEST:DEATH_PLATEAU
QUEST:LUNAR_DIPLOMACY
QUEST:THE_FREMENNIK_TRIALS
QUEST:LOST_CITY
QUEST:RUNE_MYSTERIES
QUEST:SHILO_VILLAGE
QUEST:JUNGLE_POTION
QUEST:THE_HAND_IN_THE_SAND
QUEST:WANTED
QUEST:RECRUITMENT_DRIVE
QUEST:BLACK_KNIGHTS_FORTRESS
QUEST:THE_LOST_TRIBE
QUEST:GOBLIN_DIPLOMACY
QUEST:TEMPLE_OF_THE_EYE
QUEST:ENTER_THE_ABYSS
#QUEST:TEARS_OF_GUTHIX  # Not available in configuration
QUEST:NATURE_SPIRIT
#QUEST:A_TAIL_OF_TWO_CATS  # Not available in configuration
QUEST:ICTHLARINS_LITTLE_HELPER
QUEST:GERTRUDES_CAT