import type { QuestsConfig } from './types';

export const questsConfig: QuestsConfig = {
  "COOKS_ASSISTANT": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "DORICS_QUEST": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "DRUIDIC_RITUAL": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "IMP_CATCHER": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "DWARF_CANNON": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "NATURAL_HISTORY_QUIZ": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "ROMEO_AND_JULIET": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "SEA_SLUG": {"requirements": {"skills": {"firemaking": 30}, "quests": [], "other": []}},
  "SHEEP_SHEARER": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "THE_FEUD": {"requirements": {"skills": {"thieving": 30, "hitpoints": 15, "magic": 35}, "quests": [], "other": ["Fire Bolt spell"]}},
  "WITCHS_HOUSE": {"requirements": {"skills": {"magic": 9}, "quests": [], "other": ["Earth Strike spell"]}},
  "WITCHS_POTION": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "BLACK_KNIGHTS_FORTRESS": {"requirements": {"skills": {}, "quests": [], "other": ["12 Quest points"]}},
  "GERTRUDES_CAT": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "HORROR_FROM_THE_DEEP": {"requirements": {"skills": {"agility": 35, "magic": 35}, "quests": ["BARCRAWL"], "other": []}},
  "ELEMENTAL_WORKSHOP_I": {"requirements": {"skills": {"mining": 20, "smithing": 20, "crafting": 20}, "quests": [], "other": []}},
  "DEATH_PLATEAU": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "TROLL_STRONGHOLD": {"requirements": {"skills": {"prayer": 43, "magic": 30}, "quests": ["DEATH_PLATEAU"], "other": []}},
  "X_MARKS_THE_SPOT": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "BARCRAWL": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "CLIENT_OF_KOUREND": {"requirements": {"skills": {}, "quests": ["X_MARKS_THE_SPOT"], "other": []}},
  "THE_RESTLESS_GHOST": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "RUNE_MYSTERIES": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "VAMPYRE_SLAYER": {"requirements": {"skills": {"magic": 9}, "quests": [], "other": ["Earth Strike spell"]}},
  "WATERFALL_QUEST": {"requirements": {"skills": {}, "quests": [], "other": ["43 prayer and/or 20+ hitpoints recommended"]}},
  "PLAGUE_CITY": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "BIOHAZARD": {"requirements": {"skills": {"magic": 9}, "quests": ["PLAGUE_CITY"], "other": ["Earth Strike spell"]}},
  "THE_KNIGHTS_SWORD": {"requirements": {"skills": {"mining": 10}, "quests": [], "other": []}},
  "ERNEST_THE_CHICKEN": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "MONKS_FRIEND": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "FIGHT_ARENA": {"requirements": {"skills": {"magic": 9, "hitpoints": 20}, "quests": [], "other": []}},
  "TREE_GNOME_VILLAGE": {"requirements": {"skills": {"magic": 9, "hitpoints": 20}, "quests": [], "other": []}},
  "PRIEST_IN_PERIL": {"requirements": {"skills": {"hitpoints": 20}, "quests": [], "other": ["Enough melee stats to kill temple guardian"]}},
  "NATURE_SPIRIT": {"requirements": {"skills": {"magic": 35, "hitpoints": 20, "prayer": 43}, "quests": [], "other": []}},
  "RFD_COOK": {"requirements": {"skills": {"cooking": 10}, "quests": ["COOKS_ASSISTANT"], "other": []}},
  "RFD_DWARF": {"requirements": {"skills": {}, "quests": ["RFD_COOK", "FISHING_CONTEST", "COOKS_ASSISTANT"], "other": []}},
  "FISHING_CONTEST": {"requirements": {"skills": {"fishing": 10}, "quests": [], "other": []}},
  "A_PORCINE_OF_INTEREST": {"requirements": {"skills": {"magic": 35, "hitpoints": 20}, "quests": [], "other": []}},
  "ANIMAL_MAGNETISM": {"requirements": {"skills": {"crafting": 18, "ranged": 30, "woodcutting": 35, "slayer": 18}, "quests": ["THE_RESTLESS_GHOST", "PRIEST_IN_PERIL", "ERNEST_THE_CHICKEN"], "other": []}},
  "MERLINS_CRYSTAL": {"requirements": {"skills": {"magic": 35, "hitpoints": 20}, "quests": [], "other": []}},
  "HOLY_GRAIL": {"requirements": {"skills": {"magic": 35, "hitpoints": 20}, "quests": ["MERLINS_CRYSTAL"], "other": []}},
  "DRAGON_SLAYER_I": {"requirements": {"skills": {"magic": 41, "prayer": 43}, "quests": [], "other": ["42 quest points", "Enough stats to not get rekt by Elvarg"]}},
  "LOST_CITY": {"requirements": {"skills": {"crafting": 31, "woodcutting": 36, "magic": 39}, "quests": [], "other": []}},
  "WHAT_LIES_BELOW": {"requirements": {"skills": {"magic": 35, "hitpoints": 20, "runecrafting": 35, "mining": 42}, "quests": [], "other": []}},
  "THE_DIG_SITE": {"requirements": {"skills": {"agility": 10, "herblore": 10, "thieving": 25}, "quests": [], "other": []}},
  "THE_GRAND_TREE": {"requirements": {"skills": {"magic": 13, "agility": 25}, "quests": ["TREE_GNOME_VILLAGE"], "other": []}},
  "GOBLIN_DIPLOMACY": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "RFD_GOBLINS": {"requirements": {"skills": {}, "quests": ["GOBLIN_DIPLOMACY", "RFD_COOK"], "other": []}},
  "FAIRYTALE_I": {"requirements": {"skills": {"prayer": 43}, "quests": ["LOST_CITY", "NATURE_SPIRIT", "JUNGLE_POTION"], "other": ["Enough stats to kill tanglefoot"]}},
  "BONE_VOYAGE": {"requirements": {"skills": {}, "quests": ["THE_DIG_SITE", "RUNE_MYSTERIES", "THE_GRAND_TREE", "PRIEST_IN_PERIL", "TEMPLE_OF_IKOV", "MERLINS_CRYSTAL", "SHIELD_OF_ARRAV", "HAZEEL_CULT", "DEMON_SLAYER", "OBSERVATORY_QUEST"], "other": ["100 kudos", "5 of the listed quests for kudos"]}},
  "JUNGLE_POTION": {"requirements": {"skills": {"herblore": 3}, "quests": [], "other": ["Enough stats to not get rekt by mosquitos/ogres"]}},
  "THE_ASCENT_OF_ARCEUUS": {"requirements": {"skills": {"hunter": 12, "magic": 39}, "quests": ["CLIENT_OF_KOUREND"], "other": []}},
  "SHILO_VILLAGE": {"requirements": {"skills": {"crafting": 20, "agility": 32}, "quests": ["JUNGLE_POTION"], "other": ["Higher agility recommended"]}},
  "ONE_SMALL_FAVOUR": {"requirements": {"skills": {"smithing": 30, "herblore": 18, "crafting": 25, "agility": 36}, "quests": ["SHILO_VILLAGE", "RUNE_MYSTERIES"], "other": []}},
  "MURDER_MYSTERY": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "KINGS_RANSOM": {"requirements": {"skills": {"defence": 65, "magic": 45}, "quests": ["MURDER_MYSTERY", "HOLY_GRAIL", "ONE_SMALL_FAVOUR", "BLACK_KNIGHTS_FORTRESS"], "other": []}},
  "THE_TOURIST_TRAP": {"requirements": {"skills": {"fletching": 10, "smithing": 20}, "quests": [], "other": ["Stats to kill the guard"]}},
  "TEMPLE_OF_IKOV": {"requirements": {"skills": {"thieving": 42, "ranged": 30, "prayer": 43}, "quests": [], "other": []}},
  "DESERT_TREASURE_I": {"requirements": {"skills": {"magic": 62, "prayer": 43, "hitpoints": 28}, "quests": [], "other": ["DT1 requirements"]}},
  "THE_FREMENNIK_TRIALS": {"requirements": {"skills": {"prayer": 43, "magic": 29}, "quests": [], "other": ["Enough combat stats for Koschei battle"]}},
  "OBSERVATORY_QUEST": {"requirements": {"skills": {"hitpoints": 20, "magic": 20}, "quests": [], "other": []}},
  "DEMON_SLAYER": {"requirements": {"skills": {"attack": 20, "strength": 20, "hitpoints": 20}, "quests": [], "other": []}},
  "UNDERGROUND_PASS": {"requirements": {"skills": {"prayer": 43, "agility": 50, "ranged": 25}, "quests": ["BIOHAZARD"], "other": ["80+ combat recommended", "Higher agility recommended"]}},
  "THE_GOLEM": {"requirements": {"skills": {"crafting": 20, "thieving": 25}, "quests": [], "other": []}},
  "SHADOW_OF_THE_STORM": {"requirements": {"skills": {"crafting": 30}, "quests": ["THE_GOLEM", "DEMON_SLAYER"], "other": ["Stats to flinch Agrith Naar"]}},
  "GHOSTS_AHOY": {"requirements": {"skills": {"agility": 25, "cooking": 20}, "quests": ["PRIEST_IN_PERIL", "THE_RESTLESS_GHOST"], "other": []}},
  "MAKING_HISTORY": {"requirements": {"skills": {}, "quests": ["PRIEST_IN_PERIL", "THE_RESTLESS_GHOST"], "other": []}},
  "MOUNTAIN_DAUGHTER": {"requirements": {"skills": {"magic": 9, "agility": 20}, "quests": [], "other": []}},
  "HAZEEL_CULT": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "CHILDREN_OF_THE_SUN": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "PRINCE_ALI_RESCUE": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "ICTHLARINS_LITTLE_HELPER": {"requirements": {"skills": {}, "quests": ["GERTRUDES_CAT"], "other": ["Enough magic level to kill the bosses"]}},
  "ENTER_THE_ABYSS": {"requirements": {"skills": {}, "quests": ["RUNE_MYSTERIES"], "other": []}},
  "TEMPLE_OF_THE_EYE": {"requirements": {"skills": {}, "quests": ["ENTER_THE_ABYSS"], "other": []}},
  "CREATURE_OF_FENKENSTRAIN": {"requirements": {"skills": {"crafting": 20, "thieving": 25}, "quests": ["PRIEST_IN_PERIL", "THE_RESTLESS_GHOST"], "other": []}},
  "THE_DEPTHS_OF_DESPAIR": {"requirements": {"skills": {"agility": 18}, "quests": ["CLIENT_OF_KOUREND"], "other": []}},
  "THE_QUEEN_OF_THIEVES": {"requirements": {"skills": {"thieving": 20}, "quests": ["CLIENT_OF_KOUREND"], "other": []}},
  "ENLIGHTENED_JOURNEY": {"requirements": {"skills": {"firemaking": 20, "farming": 30, "crafting": 36}, "quests": [], "other": ["20 quest points"]}},
  "SHEEP_HERDER": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "BIG_CHOMPY_BIRD_HUNTING": {"requirements": {"skills": {"ranged": 30, "cooking": 30, "fletching": 5}, "quests": [], "other": []}},
  "RFD_OGRE": {"requirements": {"skills": {"cooking": 41, "firemaking": 20}, "quests": ["BIG_CHOMPY_BIRD_HUNTING"], "other": []}},
  "RFD_EVIL_DAVE": {"requirements": {"skills": {"cooking": 25}, "quests": ["GERTRUDES_CAT", "SHADOW_OF_THE_STORM", "RFD_COOK"], "other": []}},
  "RFD_PIRATE": {"requirements": {"skills": {"cooking": 31}, "quests": ["RFD_COOK"], "other": []}},
  "RFD_GUIDE": {"requirements": {"skills": {"cooking": 40}, "quests": ["RFD_COOK", "BIOHAZARD", "NATURE_SPIRIT", "MURDER_MYSTERY", "DEMON_SLAYER", "WITCHS_HOUSE", "BIG_CHOMPY_BIRD_HUNTING"], "other": []}},
  "RFD_MONKEY": {"requirements": {"skills": {"cooking": 70, "agility": 48, "magic": 55}, "quests": ["RFD_COOK", "MONKEY_MADNESS_I"], "other": []}},
  "RFD_AMIK_VARZE": {"requirements": {"skills": {}, "quests": [], "other": ["All quest requirements except legends quest"]}},
  "RFD_CULINAROMANCER": {"requirements": {"skills": {}, "quests": ["RFD_COOK", "RFD_DWARF", "RFD_GOBLINS", "RFD_EVIL_DAVE", "RFD_PIRATE", "RFD_GUIDE", "RFD_MONKEY", "RFD_OGRE", "RFD_AMIK_VARZE"], "other": ["175 Quest Points", "All RFD subquests"]}},
  "SHIELD_OF_ARRAV": {"requirements": {"skills": {}, "quests": [], "other": ["Websocket matchmaking to find a pair"]}},
  "HEROES_QUEST": {"requirements": {"skills": {}, "quests": [], "other": ["Heroes quest requirements", "Websocket matchmaking to find a pair"]}},
  "TOWER_OF_LIFE": {"requirements": {"skills": {"construction": 10}, "quests": [], "other": []}},
  "CLOCK_TOWER": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "TRIBAL_TOTEM": {"requirements": {"skills": {"thieving": 21}, "quests": [], "other": []}},
  "WATCHTOWER": {"requirements": {"skills": {"magic": 14, "thieving": 15, "agility": 25, "herblore": 14, "mining": 40}, "quests": [], "other": []}},
  "GETTING_AHEAD": {"requirements": {"skills": {"crafting": 30, "construction": 26}, "quests": [], "other": []}},
  "PIRATES_TREASURE": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "SCORPION_CATCHER": {"requirements": {"skills": {"prayer": 31}, "quests": ["BARCRAWL"], "other": []}},
  "THE_CORSAIR_CURSE": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "FAMILY_CREST": {"requirements": {"skills": {"mining": 40, "smithing": 40, "magic": 59, "crafting": 40}, "quests": [], "other": []}},
  "THE_GARDEN_OF_DEATH": {"requirements": {"skills": {"farming": 20}, "quests": [], "other": []}},
  "MONKEY_MADNESS_I": {"requirements": {"skills": {"prayer": 43}, "quests": ["THE_GRAND_TREE", "TREE_GNOME_VILLAGE"], "other": []}},
  "THE_FORSAKEN_TOWER": {"requirements": {"skills": {}, "quests": ["CLIENT_OF_KOUREND"], "other": []}},
  "HAUNTED_MINE": {"requirements": {"skills": {"magic": 39, "hitpoints": 28, "crafting": 35}, "quests": ["PRIEST_IN_PERIL", "THE_RESTLESS_GHOST"], "other": ["Higher hitpoints recommended"]}},
  "TALE_OF_THE_RIGHTEOUS": {"requirements": {"skills": {"strength": 16, "mining": 10}, "quests": ["CLIENT_OF_KOUREND"], "other": ["Stats to mage a 46cb lizard"]}},
  "SLEEPING_GIANTS": {"requirements": {"skills": {"smithing": 15}, "quests": [], "other": []}},
  "TROLL_ROMANCE": {"requirements": {"skills": {"agility": 28, "prayer": 43}, "quests": ["TROLL_STRONGHOLD"], "other": []}},
  "THE_LOST_TRIBE": {"requirements": {"skills": {"agility": 13, "thieving": 13, "mining": 17}, "quests": ["GOBLIN_DIPLOMACY", "RUNE_MYSTERIES"], "other": []}},
  "RECRUITMENT_DRIVE": {"requirements": {"skills": {"attack": 5, "strength": 5}, "quests": ["BLACK_KNIGHTS_FORTRESS", "DRUIDIC_RITUAL"], "other": ["Higher stats recommended"]}},
  "A_KINGDOM_DIVIDED": {"requirements": {"skills": {"attack": 50, "strength": 50, "magic": 50, "ranged": 50}, "quests": [], "other": ["See wiki for full requirements"]}},
  "DEATH_ON_THE_ISLE": {"requirements": {"skills": {"thieving": 34, "agility": 32}, "quests": [], "other": []}},
  "WANTED": {"requirements": {"skills": {}, "quests": ["RECRUITMENT_DRIVE", "THE_LOST_TRIBE", "PRIEST_IN_PERIL", "ENTER_THE_ABYSS"], "other": ["32 quest points"]}},
  "TWILIGHTS_PROMISE": {"requirements": {"skills": {}, "quests": ["CHILDREN_OF_THE_SUN"], "other": ["30+ combat level recommended"]}},
  "REGICIDE": {"requirements": {"skills": {"agility": 56, "crafting": 10}, "quests": ["UNDERGROUND_PASS"], "other": []}},
  "ROVING_ELVES": {"requirements": {"skills": {}, "quests": ["REGICIDE"], "other": []}},
  "MOURNINGS_END_PART_I": {"requirements": {"skills": {"ranged": 60, "thieving": 50}, "quests": ["ROVING_ELVES"], "other": []}},
  "MOURNINGS_END_PART_II": {"requirements": {"skills": {"agility": 65}, "quests": ["MOURNINGS_END_PART_I"], "other": ["Higher agility recommended"]}},
  "ETHICALLY_ACQUIRED_ANTIQUITIES": {"requirements": {"skills": {"thieving": 25}, "quests": ["CHILDREN_OF_THE_SUN", "SHIELD_OF_ARRAV"], "other": []}},
  "DADDYS_HOME": {"requirements": {"skills": {}, "quests": [], "other": []}},
  "LUNAR_DIPLOMACY": {"requirements": {"skills": {"magic": 14, "thieving": 15, "agility": 25, "herblore": 14, "mining": 40}, "quests": [], "other": []}},
  "IN_SEARCH_OF_THE_MYREQUE": {"requirements": {"skills": {"agility": 25}, "quests": ["NATURE_SPIRIT"], "other": []}},
  "THRONE_OF_MISCELLANIA": {"requirements": {"skills": {"woodcutting": 45, "farming": 10, "herblore": 35}, "quests": ["THE_FREMENNIK_TRIALS", "HEROES_QUEST"], "other": []}},
  "ROYAL_TROUBLE": {"requirements": {"skills": {"agility": 40, "slayer": 40}, "quests": ["THRONE_OF_MISCELLANIA"], "other": []}},
  "THE_HAND_IN_THE_SAND": {"requirements": {"skills": {"thieving": 17, "crafting": 49}, "quests": [], "other": []}},
  "ZOGRE_FLESH_EATERS": {"requirements": {"skills": {"smithing": 4, "herblore": 8}, "quests": ["JUNGLE_POTION", "BIG_CHOMPY_BIRD_HUNTING"], "other": []}},
  "RUM_DEAL": {"requirements": {"skills": {"crafting": 42, "fishing": 50, "farming": 40, "prayer": 47, "slayer": 42}, "quests": ["PRIEST_IN_PERIL", "ZOGRE_FLESH_EATERS"], "other": []}},
  "CABIN_FEVER": {"requirements": {"skills": {"agility": 42, "crafting": 45, "smithing": 50, "ranged": 40}, "quests": ["PIRATES_TREASURE", "RUM_DEAL"], "other": []}},
  "THE_EYES_OF_GLOUPHRIE": {"requirements": {"skills": {"magic": 46, "construction": 5, "runecrafting": 13}, "quests": ["THE_GRAND_TREE"], "other": []}}
};